/**
 * Generate a self-contained HTML audit report from markdown output.
 * Dark theme matching sverklo.com branding. No external dependencies.
 */

export function generateAuditHtml(
  markdownContent: string,
  projectName: string,
  projectPath: string
): string {
  const now = new Date().toISOString().slice(0, 19).replace("T", " ");

  // Escape HTML in the markdown content
  const escaped = markdownContent
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");

  // Convert markdown to simple HTML
  const htmlBody = markdownToHtml(escaped);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Sverklo Audit — ${esc(projectName)}</title>
<style>
  :root {
    --bg: #0E0D0B;
    --bg2: #1a1916;
    --text: #EDE7D9;
    --text2: #A39886;
    --accent: #E85A2A;
    --green: #4ade80;
    --yellow: #facc15;
    --red: #ef4444;
  }
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    background: var(--bg);
    color: var(--text);
    font-family: 'JetBrains Mono', 'Fira Code', 'SF Mono', Consolas, monospace;
    font-size: 14px;
    line-height: 1.6;
    padding: 40px 20px;
    max-width: 900px;
    margin: 0 auto;
  }
  .header {
    border-bottom: 2px solid var(--accent);
    padding-bottom: 24px;
    margin-bottom: 32px;
  }
  .header h1 {
    font-size: 28px;
    color: var(--text);
    margin-bottom: 8px;
  }
  .header h1 span { color: var(--accent); }
  .header .meta {
    color: var(--text2);
    font-size: 12px;
  }
  h2 {
    color: var(--accent);
    font-size: 18px;
    margin: 32px 0 16px;
    padding-bottom: 8px;
    border-bottom: 1px solid #333;
  }
  h3 {
    color: var(--text);
    font-size: 15px;
    margin: 20px 0 8px;
  }
  p { margin: 8px 0; }
  ul, ol { margin: 8px 0 8px 20px; }
  li { margin: 4px 0; }
  code {
    background: var(--bg2);
    padding: 2px 6px;
    border-radius: 3px;
    font-size: 13px;
  }
  pre {
    background: var(--bg2);
    padding: 16px;
    border-radius: 6px;
    overflow-x: auto;
    margin: 12px 0;
    border-left: 3px solid var(--accent);
  }
  table {
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
    font-size: 13px;
  }
  th {
    background: var(--bg2);
    color: var(--accent);
    text-align: left;
    padding: 8px 12px;
    border-bottom: 2px solid var(--accent);
  }
  td {
    padding: 6px 12px;
    border-bottom: 1px solid #222;
  }
  tr:hover td { background: var(--bg2); }
  .footer {
    margin-top: 48px;
    padding-top: 24px;
    border-top: 1px solid #333;
    text-align: center;
    color: var(--text2);
    font-size: 12px;
  }
  .footer a {
    color: var(--accent);
    text-decoration: none;
  }
  .footer a:hover { text-decoration: underline; }
  strong { color: var(--text); }
  em { color: var(--text2); font-style: italic; }
  a { color: var(--accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  @media (max-width: 600px) {
    body { padding: 20px 12px; font-size: 13px; }
    .header h1 { font-size: 22px; }
  }
</style>
</head>
<body>
<div class="header">
  <h1><span>sverklo</span> audit</h1>
  <div class="meta">
    ${esc(projectName)} · ${esc(projectPath)}<br>
    Generated ${now} · Sverklo v0.4.0
  </div>
</div>

${htmlBody}

<div class="footer">
  Generated by <a href="https://sverklo.com">Sverklo</a> — local-first code intelligence<br>
  <code>npm install -g sverklo</code>
</div>
</body>
</html>`;
}

function esc(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function markdownToHtml(md: string): string {
  const lines = md.split("\n");
  const out: string[] = [];
  let inList = false;
  let inTable = false;

  for (const line of lines) {
    // Headings
    if (line.startsWith("### ")) {
      if (inList) { out.push("</ul>"); inList = false; }
      if (inTable) { out.push("</table>"); inTable = false; }
      out.push(`<h3>${inline(line.slice(4))}</h3>`);
      continue;
    }
    if (line.startsWith("## ")) {
      if (inList) { out.push("</ul>"); inList = false; }
      if (inTable) { out.push("</table>"); inTable = false; }
      out.push(`<h2>${inline(line.slice(3))}</h2>`);
      continue;
    }

    // Table rows
    if (line.startsWith("|")) {
      if (line.replace(/[|\-\s]/g, "").length === 0) continue; // separator
      const cells = line.split("|").filter(Boolean).map(c => c.trim());
      if (!inTable) {
        out.push("<table><tr>");
        cells.forEach(c => out.push(`<th>${inline(c)}</th>`));
        out.push("</tr>");
        inTable = true;
      } else {
        out.push("<tr>");
        cells.forEach(c => out.push(`<td>${inline(c)}</td>`));
        out.push("</tr>");
      }
      continue;
    }
    if (inTable && !line.startsWith("|")) {
      out.push("</table>");
      inTable = false;
    }

    // List items
    if (/^\s*[-·•]\s/.test(line)) {
      if (!inList) { out.push("<ul>"); inList = true; }
      out.push(`<li>${inline(line.replace(/^\s*[-·•]\s/, ""))}</li>`);
      continue;
    }
    if (inList && line.trim() === "") {
      out.push("</ul>");
      inList = false;
      continue;
    }

    // Empty line
    if (line.trim() === "") {
      continue;
    }

    // Paragraph
    if (inList) { out.push("</ul>"); inList = false; }
    out.push(`<p>${inline(line)}</p>`);
  }

  if (inList) out.push("</ul>");
  if (inTable) out.push("</table>");

  return out.join("\n");
}

function inline(text: string): string {
  return text
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/_(.+?)_/g, "<em>$1</em>")
    .replace(/`([^`]+)`/g, "<code>$1</code>");
}
